//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationWindow.SendSmsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendSmsServiceReference.ISmsService")]
    public interface ISmsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsService/SendSms", ReplyAction="http://tempuri.org/ISmsService/SendSmsResponse")]
        bool SendSms(string phone, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsService/SendSms", ReplyAction="http://tempuri.org/ISmsService/SendSmsResponse")]
        System.Threading.Tasks.Task<bool> SendSmsAsync(string phone, string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmsServiceChannel : RegistrationWindow.SendSmsServiceReference.ISmsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsServiceClient : System.ServiceModel.ClientBase<RegistrationWindow.SendSmsServiceReference.ISmsService>, RegistrationWindow.SendSmsServiceReference.ISmsService {
        
        public SmsServiceClient() {
        }
        
        public SmsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendSms(string phone, string text) {
            return base.Channel.SendSms(phone, text);
        }
        
        public System.Threading.Tasks.Task<bool> SendSmsAsync(string phone, string text) {
            return base.Channel.SendSmsAsync(phone, text);
        }
    }
}
